version: "3"
services:
  app:
    build: ../
    ports:
      - "8080:80"
    environment:
      BASE_URL: https://{{ services.api.url }}
      AUTH_SECRET: sTr0NGs3cr3t
      DATABASE_URL: Server=postgres_db;Port=5432;User Id=aptabase;Password=aptabase_pw;Database=aptabase
      CLICKHOUSE_URL: Host=clickhouse_db;Port=8123;Username=aptabase;Password=aptabase_pw

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: aptabase_pw
    ports:
      - 5432

  clickhouse_db:
    container_name: aptabase_clickhousedev
    image: clickhouse/clickhouse-server:23.3.8.21
    restart: always
    ports:
      - 8123
    environment:
      CLICKHOUSE_USER: aptabase
      CLICKHOUSE_PASSWORD: aptabase_pw
